### ISSUE TITLE
Error: could not find function "dmap_if"

### ISSUE THREAD

**Issue by tungttnguyen** [jbkunst/highcharter-shiny#2]
I think `dmap_if` was moved to [`purrrlyr`](https://github.com/hadley/purrrlyr) package so `nytemp` app doesn't work anymore

**Comment by jbkunst** [comment]
Yep, dmap_if and purrrly is not used anymore.

Can you be a little specific and tell me where the packages uses that function?

Thanks

**Comment by jbkunst** [comment]
Sorry! Yep, it's an old code. You can _update_ the code using `mutate_if` from the dplyr package instead of ´dmap_if´
